"""Broker execution error codes (Alpaca paper submit path)."""

from __future__ import annotations


PIPELINE_PRECONDITION_FAILED = "PIPELINE_PRECONDITION_FAILED"
BROKER_ACCOUNT_DISABLED = "BROKER_ACCOUNT_DISABLED"
LIVE_BROKER_ACCESS_FORBIDDEN = "LIVE_BROKER_ACCESS_FORBIDDEN"
PAPER_ACCOUNT_NOT_VERIFIED = "PAPER_ACCOUNT_NOT_VERIFIED"
INSUFFICIENT_BROKER_BUYING_POWER = "INSUFFICIENT_BROKER_BUYING_POWER"
ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"
TRADING_BLOCKED = "TRADING_BLOCKED"
UNSUPPORTED_ASSET_CLASS = "UNSUPPORTED_ASSET_CLASS"
UNSUPPORTED_ORDER_TYPE = "UNSUPPORTED_ORDER_TYPE"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
RATE_LIMITED = "RATE_LIMITED"
BROKER_UNAVAILABLE = "BROKER_UNAVAILABLE"
NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
MALFORMED_RESPONSE = "MALFORMED_RESPONSE"
AMBIGUOUS_IDEMPOTENCY_STATE = "AMBIGUOUS_IDEMPOTENCY_STATE"
STALE_MARKET_DATA = "STALE_MARKET_DATA"
PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
ORDER_REJECTED_BY_BROKER = "ORDER_REJECTED_BY_BROKER"
SUBMIT_FORBIDDEN = "SUBMIT_FORBIDDEN"


class ExecutionAdapterError(Exception):
    def __init__(self, message: str, *, code: str) -> None:
        self.message = message
        self.code = code
        super().__init__(message)
