"""Stable reason codes for Risk Engine and related pipeline decisions."""

from __future__ import annotations

# Account / mode
BROKER_ACCOUNT_NOT_FOUND = "BROKER_ACCOUNT_NOT_FOUND"
BROKER_ACCOUNT_DISABLED = "BROKER_ACCOUNT_DISABLED"
LIVE_TRADING_NOT_ALLOWED = "LIVE_TRADING_NOT_ALLOWED"

# Strategy / assignment
STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
STRATEGY_PAUSED = "STRATEGY_PAUSED"
STRATEGY_RETIRED = "STRATEGY_RETIRED"
STRATEGY_NOT_ASSIGNED = "STRATEGY_NOT_ASSIGNED"
STRATEGY_ASSIGNMENT_DISABLED = "STRATEGY_ASSIGNMENT_DISABLED"
STRATEGY_ASSIGNMENT_LIVE_NOT_ALLOWED = "STRATEGY_ASSIGNMENT_LIVE_NOT_ALLOWED"

# Limits / structure
STOP_LOSS_REQUIRED = "STOP_LOSS_REQUIRED"
QUANTITY_INVALID = "QUANTITY_INVALID"
MAX_POSITION_SIZE_EXCEEDED = "MAX_POSITION_SIZE_EXCEEDED"
MAX_ORDER_VALUE_EXCEEDED = "MAX_ORDER_VALUE_EXCEEDED"
MAX_OPEN_POSITIONS_EXCEEDED = "MAX_OPEN_POSITIONS_EXCEEDED"
MAX_DAILY_LOSS_EXCEEDED = "MAX_DAILY_LOSS_EXCEEDED"
DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
MAX_TOTAL_EXPOSURE_EXCEEDED = "MAX_TOTAL_EXPOSURE_EXCEEDED"
DUPLICATE_PROPOSAL = "DUPLICATE_PROPOSAL"

# Evaluation transparency
NOT_EVALUATED = "NOT_EVALUATED"
NOT_EVALUATED_MARKET_PRICE_REQUIRED = "NOT_EVALUATED_MARKET_PRICE_REQUIRED"
NOT_EVALUATED_PRICE_REQUIRED = "NOT_EVALUATED_PRICE_REQUIRED"
STALE_MARKET_DATA = "STALE_MARKET_DATA"
PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"

# Fail-closed
RISK_ENGINE_ERROR = "RISK_ENGINE_ERROR"
ORDER_VALIDATION_ERROR = "ORDER_VALIDATION_ERROR"
BROKER_ROUTER_ERROR = "BROKER_ROUTER_ERROR"
UNSUPPORTED_BROKER = "UNSUPPORTED_BROKER"
INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
PROPOSAL_NOT_RISK_APPROVED = "PROPOSAL_NOT_RISK_APPROVED"
PROPOSAL_NOT_VALIDATED = "PROPOSAL_NOT_VALIDATED"
PROPOSAL_ALREADY_ROUTED = "PROPOSAL_ALREADY_ROUTED"

# Alpaca paper execution
INSUFFICIENT_BROKER_BUYING_POWER = "INSUFFICIENT_BROKER_BUYING_POWER"
PAPER_ACCOUNT_NOT_VERIFIED = "PAPER_ACCOUNT_NOT_VERIFIED"
LIVE_BROKER_ACCESS_FORBIDDEN = "LIVE_BROKER_ACCESS_FORBIDDEN"
ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED"
TRADING_BLOCKED = "TRADING_BLOCKED"
UNSUPPORTED_ASSET_CLASS = "UNSUPPORTED_ASSET_CLASS"
AMBIGUOUS_IDEMPOTENCY_STATE = "AMBIGUOUS_IDEMPOTENCY_STATE"
PIPELINE_PRECONDITION_FAILED = "PIPELINE_PRECONDITION_FAILED"
